# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class AdditionalRelationships(str, enum.Enum):
    POSSIBLY_SAME_AS = "possibly_same_as"

    def visit(self, possibly_same_as: typing.Callable[[], T_Result]) -> T_Result:
        if self is AdditionalRelationships.POSSIBLY_SAME_AS:
            return possibly_same_as()
