# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ....core.datetime_utils import serialize_datetime
from ...generated_types.types.country import Country

try:
    import pydantic.v1 as pydantic  # type: ignore
except ImportError:
    import pydantic  # type: ignore


class TradeFilterList(pydantic.BaseModel):
    """
    Filter your search on the following attributes.
    """

    buyer_id: typing.Optional[typing.List[str]]
    supplier_id: typing.Optional[typing.List[str]]
    buyer_name: typing.Optional[typing.List[str]]
    supplier_name: typing.Optional[typing.List[str]]
    buyer_risk: typing.Optional[typing.List[str]]
    supplier_risk: typing.Optional[typing.List[str]]
    buyer_country: typing.Optional[typing.List[Country]]
    supplier_country: typing.Optional[typing.List[Country]]
    departure_country: typing.Optional[typing.List[Country]]
    departure_state: typing.Optional[typing.List[str]]
    departure_city: typing.Optional[typing.List[str]]
    arrival_country: typing.Optional[typing.List[Country]]
    arrival_state: typing.Optional[typing.List[str]]
    arrival_city: typing.Optional[typing.List[str]]
    hs_code: typing.Optional[typing.List[str]]
    hs_description: typing.Optional[typing.List[str]]
    supplier_purpose: typing.Optional[typing.List[str]]
    buyer_purpose: typing.Optional[typing.List[str]]
    arrival_date: typing.Optional[typing.List[str]]
    weight: typing.Optional[typing.List[str]]
    sources: typing.Optional[typing.List[str]]

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        smart_union = True
        json_encoders = {dt.datetime: serialize_datetime}
