# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class ReferencedByDataType(str, enum.Enum):
    ABOUT = "about"
    MENTIONS = "mentions"

    def visit(self, about: typing.Callable[[], T_Result], mentions: typing.Callable[[], T_Result]) -> T_Result:
        if self is ReferencedByDataType.ABOUT:
            return about()
        if self is ReferencedByDataType.MENTIONS:
            return mentions()
