# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
from ...generated_types.types.both_identifier_types import BothIdentifierTypes
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import typing
import pydantic


class ShipmentIdentifier(UniversalBaseModel):
    value: str
    type: BothIdentifierTypes

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
