# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
from .ontology_countries_filters import OntologyCountriesFilters
import typing
from .ontology_country import OntologyCountry
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class GetOntologyCountriesResponse(UniversalBaseModel):
    """
    Examples
    --------
    from sayari.ontology import (
        GetOntologyCountriesResponse,
        OntologyCountriesFilters,
        OntologyCountry,
    )

    GetOntologyCountriesResponse(
        filters=OntologyCountriesFilters(
            id=["USA"],
        ),
        data=[
            OntologyCountry(
                id="USA",
                label="United States",
                code=13988,
            )
        ],
        total_count=1234,
    )
    """

    filters: OntologyCountriesFilters
    data: typing.List[OntologyCountry]
    total_count: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
