# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class CompanyStatus(str, enum.Enum):
    SEIZED = "seized"
    IN_RECEIVERSHIP = "in_receivership"
    REGISTRATION_REVOKED = "registration_revoked"
    OPENING = "opening"
    DISSOLVED = "dissolved"
    ACTIVE = "active"
    INACTIVE = "inactive"
    CLOSED = "closed"
    CLOSING = "closing"
    REGISTERED = "registered"
    INCORPORATED = "incorporated"
    UNDER_EXTERNAL_CONTROL = "under_external_control"
    EXPIRED = "expired"
    EXPANDED = "expanded"
    TERMINATED = "terminated"

    def visit(
        self,
        seized: typing.Callable[[], T_Result],
        in_receivership: typing.Callable[[], T_Result],
        registration_revoked: typing.Callable[[], T_Result],
        opening: typing.Callable[[], T_Result],
        dissolved: typing.Callable[[], T_Result],
        active: typing.Callable[[], T_Result],
        inactive: typing.Callable[[], T_Result],
        closed: typing.Callable[[], T_Result],
        closing: typing.Callable[[], T_Result],
        registered: typing.Callable[[], T_Result],
        incorporated: typing.Callable[[], T_Result],
        under_external_control: typing.Callable[[], T_Result],
        expired: typing.Callable[[], T_Result],
        expanded: typing.Callable[[], T_Result],
        terminated: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is CompanyStatus.SEIZED:
            return seized()
        if self is CompanyStatus.IN_RECEIVERSHIP:
            return in_receivership()
        if self is CompanyStatus.REGISTRATION_REVOKED:
            return registration_revoked()
        if self is CompanyStatus.OPENING:
            return opening()
        if self is CompanyStatus.DISSOLVED:
            return dissolved()
        if self is CompanyStatus.ACTIVE:
            return active()
        if self is CompanyStatus.INACTIVE:
            return inactive()
        if self is CompanyStatus.CLOSED:
            return closed()
        if self is CompanyStatus.CLOSING:
            return closing()
        if self is CompanyStatus.REGISTERED:
            return registered()
        if self is CompanyStatus.INCORPORATED:
            return incorporated()
        if self is CompanyStatus.UNDER_EXTERNAL_CONTROL:
            return under_external_control()
        if self is CompanyStatus.EXPIRED:
            return expired()
        if self is CompanyStatus.EXPANDED:
            return expanded()
        if self is CompanyStatus.TERMINATED:
            return terminated()
