# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class Country(str, enum.Enum):
    """
    Country enums are normalized representations of country names. Taken from https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3#ECU
    """

    ABW = "ABW"
    """
    Aruba
    """

    AFG = "AFG"
    """
    Afghanistan
    """

    AGO = "AGO"
    """
    Angola
    """

    AIA = "AIA"
    """
    Anguilla
    """

    ALA = "ALA"
    """
    Åland Islands
    """

    ALB = "ALB"
    """
    Albania
    """

    AND = "AND"
    """
    Andorra
    """

    ARE = "ARE"
    """
    United Arab Emirates
    """

    ARG = "ARG"
    """
    Argentina
    """

    ARM = "ARM"
    """
    Armenia
    """

    ASM = "ASM"
    """
    American Samoa
    """

    ATA = "ATA"
    """
    Antarctica
    """

    ATF = "ATF"
    """
    French Southern and Antarctic Lands
    """

    ATG = "ATG"
    """
    Antigua and Barbuda
    """

    AUS = "AUS"
    """
    Australia
    """

    AUT = "AUT"
    """
    Austria
    """

    AZE = "AZE"
    """
    Azerbaijan
    """

    BDI = "BDI"
    """
    Burundi
    """

    BEL = "BEL"
    """
    Belgium
    """

    BEN = "BEN"
    """
    Benin
    """

    BFA = "BFA"
    """
    Burkina Faso
    """

    BGD = "BGD"
    """
    Bangladesh
    """

    BGR = "BGR"
    """
    Bulgaria
    """

    BHR = "BHR"
    """
    Bahrain
    """

    BHS = "BHS"
    """
    Bahamas
    """

    BIH = "BIH"
    """
    Bosnia and Herzegovina
    """

    BLM = "BLM"
    """
    Saint Barthélemy
    """

    SHN = "SHN"
    """
    Saint Helena, Ascension and Tristan da Cunha
    """

    BLR = "BLR"
    """
    Belarus
    """

    BLZ = "BLZ"
    """
    Belize
    """

    BMU = "BMU"
    """
    Bermuda
    """

    BOL = "BOL"
    """
    Bolivia
    """

    BES = "BES"
    """
    Caribbean Netherlands
    """

    BRA = "BRA"
    """
    Brazil
    """

    BRB = "BRB"
    """
    Barbados
    """

    BRN = "BRN"
    """
    Brunei
    """

    BTN = "BTN"
    """
    Bhutan
    """

    BVT = "BVT"
    """
    Bouvet Island
    """

    BWA = "BWA"
    """
    Botswana
    """

    CAF = "CAF"
    """
    Central African Republic
    """

    CAN = "CAN"
    """
    Canada
    """

    CCK = "CCK"
    """
    Cocos (Keeling) Islands
    """

    CHE = "CHE"
    """
    Switzerland
    """

    CHL = "CHL"
    """
    Chile
    """

    CHN = "CHN"
    """
    China
    """

    CIV = "CIV"
    """
    Ivory Coast
    """

    CMR = "CMR"
    """
    Cameroon
    """

    COD = "COD"
    """
    Democratic Republic of the Congo
    """

    COG = "COG"
    """
    Republic of the Congo
    """

    COK = "COK"
    """
    Cook Islands
    """

    COL = "COL"
    """
    Colombia
    """

    COM = "COM"
    """
    Comoros
    """

    CPV = "CPV"
    """
    Cape Verde
    """

    CRI = "CRI"
    """
    Costa Rica
    """

    CUB = "CUB"
    """
    Cuba
    """

    CUW = "CUW"
    """
    Curaçao
    """

    CXR = "CXR"
    """
    Christmas Island
    """

    CYM = "CYM"
    """
    Cayman Islands
    """

    CYP = "CYP"
    """
    Cyprus
    """

    CZE = "CZE"
    """
    Czechia
    """

    DEU = "DEU"
    """
    Germany
    """

    DJI = "DJI"
    """
    Djibouti
    """

    DMA = "DMA"
    """
    Dominica
    """

    DNK = "DNK"
    """
    Denmark
    """

    DOM = "DOM"
    """
    Dominican Republic
    """

    DZA = "DZA"
    """
    Algeria
    """

    ECU = "ECU"
    """
    Ecuador
    """

    EGY = "EGY"
    """
    Egypt
    """

    ERI = "ERI"
    """
    Eritrea
    """

    ESH = "ESH"
    """
    Western Sahara
    """

    ESP = "ESP"
    """
    Spain
    """

    EST = "EST"
    """
    Estonia
    """

    ETH = "ETH"
    """
    Ethiopia
    """

    FIN = "FIN"
    """
    Finland
    """

    FJI = "FJI"
    """
    Fiji
    """

    FLK = "FLK"
    """
    Falkland Islands
    """

    FRA = "FRA"
    """
    France
    """

    FRO = "FRO"
    """
    Faroe Islands
    """

    FSM = "FSM"
    """
    Micronesia
    """

    GAB = "GAB"
    """
    Gabon
    """

    GBR = "GBR"
    """
    United Kingdom
    """

    GEO = "GEO"
    """
    Georgia
    """

    GGY = "GGY"
    """
    Guernsey
    """

    GHA = "GHA"
    """
    Ghana
    """

    GIB = "GIB"
    """
    Gibraltar
    """

    GIN = "GIN"
    """
    Guinea
    """

    GLP = "GLP"
    """
    Guadeloupe
    """

    GMB = "GMB"
    """
    Gambia
    """

    GNB = "GNB"
    """
    Guinea-Bissau
    """

    GNQ = "GNQ"
    """
    Equatorial Guinea
    """

    GRC = "GRC"
    """
    Greece
    """

    GRD = "GRD"
    """
    Grenada
    """

    GRL = "GRL"
    """
    Greenland
    """

    GTM = "GTM"
    """
    Guatemala
    """

    GUF = "GUF"
    """
    French Guiana
    """

    GUM = "GUM"
    """
    Guam
    """

    GUY = "GUY"
    """
    Guyana
    """

    HKG = "HKG"
    """
    Hong Kong
    """

    HMD = "HMD"
    """
    Heard Island and McDonald Islands
    """

    HND = "HND"
    """
    Honduras
    """

    HRV = "HRV"
    """
    Croatia
    """

    HTI = "HTI"
    """
    Haiti
    """

    HUN = "HUN"
    """
    Hungary
    """

    IDN = "IDN"
    """
    Indonesia
    """

    IMN = "IMN"
    """
    Isle of Man
    """

    IND = "IND"
    """
    India
    """

    IOT = "IOT"
    """
    British Indian Ocean Territory
    """

    IRL = "IRL"
    """
    Ireland
    """

    IRN = "IRN"
    """
    Iran
    """

    IRQ = "IRQ"
    """
    Iraq
    """

    ISL = "ISL"
    """
    Iceland
    """

    ISR = "ISR"
    """
    Israel
    """

    ITA = "ITA"
    """
    Italy
    """

    JAM = "JAM"
    """
    Jamaica
    """

    JEY = "JEY"
    """
    Jersey
    """

    JOR = "JOR"
    """
    Jordan
    """

    JPN = "JPN"
    """
    Japan
    """

    KAZ = "KAZ"
    """
    Kazakhstan
    """

    KEN = "KEN"
    """
    Kenya
    """

    KGZ = "KGZ"
    """
    Kyrgyzstan
    """

    KHM = "KHM"
    """
    Cambodia
    """

    KIR = "KIR"
    """
    Kiribati
    """

    KNA = "KNA"
    """
    Saint Kitts and Nevis
    """

    KOR = "KOR"
    """
    South Korea
    """

    UNK = "UNK"
    """
    Kosovo
    """

    KWT = "KWT"
    """
    Kuwait
    """

    LAO = "LAO"
    """
    Laos
    """

    LBN = "LBN"
    """
    Lebanon
    """

    LBR = "LBR"
    """
    Liberia
    """

    LBY = "LBY"
    """
    Libya
    """

    LCA = "LCA"
    """
    Saint Lucia
    """

    LIE = "LIE"
    """
    Liechtenstein
    """

    LKA = "LKA"
    """
    Sri Lanka
    """

    LSO = "LSO"
    """
    Lesotho
    """

    LTU = "LTU"
    """
    Lithuania
    """

    LUX = "LUX"
    """
    Luxembourg
    """

    LVA = "LVA"
    """
    Latvia
    """

    MAC = "MAC"
    """
    Macau
    """

    MAF = "MAF"
    """
    Saint Martin
    """

    MAR = "MAR"
    """
    Morocco
    """

    MCO = "MCO"
    """
    Monaco
    """

    MDA = "MDA"
    """
    Moldova
    """

    MDG = "MDG"
    """
    Madagascar
    """

    MDV = "MDV"
    """
    Maldives
    """

    MEX = "MEX"
    """
    Mexico
    """

    MHL = "MHL"
    """
    Marshall Islands
    """

    MKD = "MKD"
    """
    Macedonia
    """

    MLI = "MLI"
    """
    Mali
    """

    MLT = "MLT"
    """
    Malta
    """

    MMR = "MMR"
    """
    Myanmar
    """

    MNE = "MNE"
    """
    Montenegro
    """

    MNG = "MNG"
    """
    Mongolia
    """

    MNP = "MNP"
    """
    Northern Mariana Islands
    """

    MOZ = "MOZ"
    """
    Mozambique
    """

    MRT = "MRT"
    """
    Mauritania
    """

    MSR = "MSR"
    """
    Montserrat
    """

    MTQ = "MTQ"
    """
    Martinique
    """

    MUS = "MUS"
    """
    Mauritius
    """

    MWI = "MWI"
    """
    Malawi
    """

    MYS = "MYS"
    """
    Malaysia
    """

    MYT = "MYT"
    """
    Mayotte
    """

    NAM = "NAM"
    """
    Namibia
    """

    NCL = "NCL"
    """
    New Caledonia
    """

    NER = "NER"
    """
    Niger
    """

    NFK = "NFK"
    """
    Norfolk Island
    """

    NGA = "NGA"
    """
    Nigeria
    """

    NIC = "NIC"
    """
    Nicaragua
    """

    NIU = "NIU"
    """
    Niue
    """

    NLD = "NLD"
    """
    Netherlands
    """

    NOR = "NOR"
    """
    Norway
    """

    NPL = "NPL"
    """
    Nepal
    """

    NRU = "NRU"
    """
    Nauru
    """

    NZL = "NZL"
    """
    New Zealand
    """

    OMN = "OMN"
    """
    Oman
    """

    PAK = "PAK"
    """
    Pakistan
    """

    PAN = "PAN"
    """
    Panama
    """

    PCN = "PCN"
    """
    Pitcairn Islands
    """

    PER = "PER"
    """
    Peru
    """

    PHL = "PHL"
    """
    Philippines
    """

    PLW = "PLW"
    """
    Palau
    """

    PNG = "PNG"
    """
    Papua New Guinea
    """

    POL = "POL"
    """
    Poland
    """

    PRI = "PRI"
    """
    Puerto Rico
    """

    PRK = "PRK"
    """
    North Korea
    """

    PRT = "PRT"
    """
    Portugal
    """

    PRY = "PRY"
    """
    Paraguay
    """

    PSE = "PSE"
    """
    Palestine
    """

    PYF = "PYF"
    """
    French Polynesia
    """

    QAT = "QAT"
    """
    Qatar
    """

    REU = "REU"
    """
    Réunion
    """

    ROU = "ROU"
    """
    Romania
    """

    RUS = "RUS"
    """
    Russia
    """

    RWA = "RWA"
    """
    Rwanda
    """

    SAU = "SAU"
    """
    Saudi Arabia
    """

    SDN = "SDN"
    """
    Sudan
    """

    SEN = "SEN"
    """
    Senegal
    """

    SGP = "SGP"
    """
    Singapore
    """

    SGS = "SGS"
    """
    South Georgia
    """

    SJM = "SJM"
    """
    Svalbard and Jan Mayen
    """

    SLB = "SLB"
    """
    Solomon Islands
    """

    SLE = "SLE"
    """
    Sierra Leone
    """

    SLV = "SLV"
    """
    El Salvador
    """

    SMR = "SMR"
    """
    San Marino
    """

    SOM = "SOM"
    """
    Somalia
    """

    SPM = "SPM"
    """
    Saint Pierre and Miquelon
    """

    SRB = "SRB"
    """
    Serbia
    """

    SSD = "SSD"
    """
    South Sudan
    """

    STP = "STP"
    """
    São Tomé and Príncipe
    """

    SUR = "SUR"
    """
    Suriname
    """

    SVK = "SVK"
    """
    Slovakia
    """

    SVN = "SVN"
    """
    Slovenia
    """

    SWE = "SWE"
    """
    Sweden
    """

    SWZ = "SWZ"
    """
    Eswatini
    """

    SXM = "SXM"
    """
    Sint Maarten
    """

    SYC = "SYC"
    """
    Seychelles
    """

    SYR = "SYR"
    """
    Syria
    """

    TCA = "TCA"
    """
    Turks and Caicos Islands
    """

    TCD = "TCD"
    """
    Chad
    """

    TGO = "TGO"
    """
    Togo
    """

    THA = "THA"
    """
    Thailand
    """

    TJK = "TJK"
    """
    Tajikistan
    """

    TKL = "TKL"
    """
    Tokelau
    """

    TKM = "TKM"
    """
    Turkmenistan
    """

    TLS = "TLS"
    """
    Timor-Leste
    """

    TON = "TON"
    """
    Tonga
    """

    TTO = "TTO"
    """
    Trinidad and Tobago
    """

    TUN = "TUN"
    """
    Tunisia
    """

    TUR = "TUR"
    """
    Turkey
    """

    TUV = "TUV"
    """
    Tuvalu
    """

    TWN = "TWN"
    """
    Taiwan
    """

    TZA = "TZA"
    """
    Tanzania
    """

    UGA = "UGA"
    """
    Uganda
    """

    UKR = "UKR"
    """
    Ukraine
    """

    UMI = "UMI"
    """
    United States Minor Outlying Islands
    """

    URY = "URY"
    """
    Uruguay
    """

    USA = "USA"
    """
    United States
    """

    UZB = "UZB"
    """
    Uzbekistan
    """

    VAT = "VAT"
    """
    Vatican City
    """

    VCT = "VCT"
    """
    Saint Vincent and the Grenadines
    """

    VEN = "VEN"
    """
    Venezuela
    """

    VGB = "VGB"
    """
    British Virgin Islands
    """

    VIR = "VIR"
    """
    United States Virgin Islands
    """

    VNM = "VNM"
    """
    Vietnam
    """

    VUT = "VUT"
    """
    Vanuatu
    """

    WLF = "WLF"
    """
    Wallis and Futuna
    """

    WSM = "WSM"
    """
    Samoa
    """

    YEM = "YEM"
    """
    Yemen
    """

    ZAF = "ZAF"
    """
    South Africa
    """

    ZMB = "ZMB"
    """
    Zambia
    """

    ZWE = "ZWE"
    """
    Zimbabwe
    """

    XXX = "XXX"
    """
    International
    """

    RKS = "RKS"
    """
    Kosovo
    """

    def visit(
        self,
        abw: typing.Callable[[], T_Result],
        afg: typing.Callable[[], T_Result],
        ago: typing.Callable[[], T_Result],
        aia: typing.Callable[[], T_Result],
        ala: typing.Callable[[], T_Result],
        alb: typing.Callable[[], T_Result],
        and_: typing.Callable[[], T_Result],
        are: typing.Callable[[], T_Result],
        arg: typing.Callable[[], T_Result],
        arm: typing.Callable[[], T_Result],
        asm: typing.Callable[[], T_Result],
        ata: typing.Callable[[], T_Result],
        atf: typing.Callable[[], T_Result],
        atg: typing.Callable[[], T_Result],
        aus: typing.Callable[[], T_Result],
        aut: typing.Callable[[], T_Result],
        aze: typing.Callable[[], T_Result],
        bdi: typing.Callable[[], T_Result],
        bel: typing.Callable[[], T_Result],
        ben: typing.Callable[[], T_Result],
        bfa: typing.Callable[[], T_Result],
        bgd: typing.Callable[[], T_Result],
        bgr: typing.Callable[[], T_Result],
        bhr: typing.Callable[[], T_Result],
        bhs: typing.Callable[[], T_Result],
        bih: typing.Callable[[], T_Result],
        blm: typing.Callable[[], T_Result],
        shn: typing.Callable[[], T_Result],
        blr: typing.Callable[[], T_Result],
        blz: typing.Callable[[], T_Result],
        bmu: typing.Callable[[], T_Result],
        bol: typing.Callable[[], T_Result],
        bes: typing.Callable[[], T_Result],
        bra: typing.Callable[[], T_Result],
        brb: typing.Callable[[], T_Result],
        brn: typing.Callable[[], T_Result],
        btn: typing.Callable[[], T_Result],
        bvt: typing.Callable[[], T_Result],
        bwa: typing.Callable[[], T_Result],
        caf: typing.Callable[[], T_Result],
        can: typing.Callable[[], T_Result],
        cck: typing.Callable[[], T_Result],
        che: typing.Callable[[], T_Result],
        chl: typing.Callable[[], T_Result],
        chn: typing.Callable[[], T_Result],
        civ: typing.Callable[[], T_Result],
        cmr: typing.Callable[[], T_Result],
        cod: typing.Callable[[], T_Result],
        cog: typing.Callable[[], T_Result],
        cok: typing.Callable[[], T_Result],
        col: typing.Callable[[], T_Result],
        com: typing.Callable[[], T_Result],
        cpv: typing.Callable[[], T_Result],
        cri: typing.Callable[[], T_Result],
        cub: typing.Callable[[], T_Result],
        cuw: typing.Callable[[], T_Result],
        cxr: typing.Callable[[], T_Result],
        cym: typing.Callable[[], T_Result],
        cyp: typing.Callable[[], T_Result],
        cze: typing.Callable[[], T_Result],
        deu: typing.Callable[[], T_Result],
        dji: typing.Callable[[], T_Result],
        dma: typing.Callable[[], T_Result],
        dnk: typing.Callable[[], T_Result],
        dom: typing.Callable[[], T_Result],
        dza: typing.Callable[[], T_Result],
        ecu: typing.Callable[[], T_Result],
        egy: typing.Callable[[], T_Result],
        eri: typing.Callable[[], T_Result],
        esh: typing.Callable[[], T_Result],
        esp: typing.Callable[[], T_Result],
        est: typing.Callable[[], T_Result],
        eth: typing.Callable[[], T_Result],
        fin: typing.Callable[[], T_Result],
        fji: typing.Callable[[], T_Result],
        flk: typing.Callable[[], T_Result],
        fra: typing.Callable[[], T_Result],
        fro: typing.Callable[[], T_Result],
        fsm: typing.Callable[[], T_Result],
        gab: typing.Callable[[], T_Result],
        gbr: typing.Callable[[], T_Result],
        geo: typing.Callable[[], T_Result],
        ggy: typing.Callable[[], T_Result],
        gha: typing.Callable[[], T_Result],
        gib: typing.Callable[[], T_Result],
        gin: typing.Callable[[], T_Result],
        glp: typing.Callable[[], T_Result],
        gmb: typing.Callable[[], T_Result],
        gnb: typing.Callable[[], T_Result],
        gnq: typing.Callable[[], T_Result],
        grc: typing.Callable[[], T_Result],
        grd: typing.Callable[[], T_Result],
        grl: typing.Callable[[], T_Result],
        gtm: typing.Callable[[], T_Result],
        guf: typing.Callable[[], T_Result],
        gum: typing.Callable[[], T_Result],
        guy: typing.Callable[[], T_Result],
        hkg: typing.Callable[[], T_Result],
        hmd: typing.Callable[[], T_Result],
        hnd: typing.Callable[[], T_Result],
        hrv: typing.Callable[[], T_Result],
        hti: typing.Callable[[], T_Result],
        hun: typing.Callable[[], T_Result],
        idn: typing.Callable[[], T_Result],
        imn: typing.Callable[[], T_Result],
        ind: typing.Callable[[], T_Result],
        iot: typing.Callable[[], T_Result],
        irl: typing.Callable[[], T_Result],
        irn: typing.Callable[[], T_Result],
        irq: typing.Callable[[], T_Result],
        isl: typing.Callable[[], T_Result],
        isr: typing.Callable[[], T_Result],
        ita: typing.Callable[[], T_Result],
        jam: typing.Callable[[], T_Result],
        jey: typing.Callable[[], T_Result],
        jor: typing.Callable[[], T_Result],
        jpn: typing.Callable[[], T_Result],
        kaz: typing.Callable[[], T_Result],
        ken: typing.Callable[[], T_Result],
        kgz: typing.Callable[[], T_Result],
        khm: typing.Callable[[], T_Result],
        kir: typing.Callable[[], T_Result],
        kna: typing.Callable[[], T_Result],
        kor: typing.Callable[[], T_Result],
        unk: typing.Callable[[], T_Result],
        kwt: typing.Callable[[], T_Result],
        lao: typing.Callable[[], T_Result],
        lbn: typing.Callable[[], T_Result],
        lbr: typing.Callable[[], T_Result],
        lby: typing.Callable[[], T_Result],
        lca: typing.Callable[[], T_Result],
        lie: typing.Callable[[], T_Result],
        lka: typing.Callable[[], T_Result],
        lso: typing.Callable[[], T_Result],
        ltu: typing.Callable[[], T_Result],
        lux: typing.Callable[[], T_Result],
        lva: typing.Callable[[], T_Result],
        mac: typing.Callable[[], T_Result],
        maf: typing.Callable[[], T_Result],
        mar: typing.Callable[[], T_Result],
        mco: typing.Callable[[], T_Result],
        mda: typing.Callable[[], T_Result],
        mdg: typing.Callable[[], T_Result],
        mdv: typing.Callable[[], T_Result],
        mex: typing.Callable[[], T_Result],
        mhl: typing.Callable[[], T_Result],
        mkd: typing.Callable[[], T_Result],
        mli: typing.Callable[[], T_Result],
        mlt: typing.Callable[[], T_Result],
        mmr: typing.Callable[[], T_Result],
        mne: typing.Callable[[], T_Result],
        mng: typing.Callable[[], T_Result],
        mnp: typing.Callable[[], T_Result],
        moz: typing.Callable[[], T_Result],
        mrt: typing.Callable[[], T_Result],
        msr: typing.Callable[[], T_Result],
        mtq: typing.Callable[[], T_Result],
        mus: typing.Callable[[], T_Result],
        mwi: typing.Callable[[], T_Result],
        mys: typing.Callable[[], T_Result],
        myt: typing.Callable[[], T_Result],
        nam: typing.Callable[[], T_Result],
        ncl: typing.Callable[[], T_Result],
        ner: typing.Callable[[], T_Result],
        nfk: typing.Callable[[], T_Result],
        nga: typing.Callable[[], T_Result],
        nic: typing.Callable[[], T_Result],
        niu: typing.Callable[[], T_Result],
        nld: typing.Callable[[], T_Result],
        nor: typing.Callable[[], T_Result],
        npl: typing.Callable[[], T_Result],
        nru: typing.Callable[[], T_Result],
        nzl: typing.Callable[[], T_Result],
        omn: typing.Callable[[], T_Result],
        pak: typing.Callable[[], T_Result],
        pan: typing.Callable[[], T_Result],
        pcn: typing.Callable[[], T_Result],
        per: typing.Callable[[], T_Result],
        phl: typing.Callable[[], T_Result],
        plw: typing.Callable[[], T_Result],
        png: typing.Callable[[], T_Result],
        pol: typing.Callable[[], T_Result],
        pri: typing.Callable[[], T_Result],
        prk: typing.Callable[[], T_Result],
        prt: typing.Callable[[], T_Result],
        pry: typing.Callable[[], T_Result],
        pse: typing.Callable[[], T_Result],
        pyf: typing.Callable[[], T_Result],
        qat: typing.Callable[[], T_Result],
        reu: typing.Callable[[], T_Result],
        rou: typing.Callable[[], T_Result],
        rus: typing.Callable[[], T_Result],
        rwa: typing.Callable[[], T_Result],
        sau: typing.Callable[[], T_Result],
        sdn: typing.Callable[[], T_Result],
        sen: typing.Callable[[], T_Result],
        sgp: typing.Callable[[], T_Result],
        sgs: typing.Callable[[], T_Result],
        sjm: typing.Callable[[], T_Result],
        slb: typing.Callable[[], T_Result],
        sle: typing.Callable[[], T_Result],
        slv: typing.Callable[[], T_Result],
        smr: typing.Callable[[], T_Result],
        som: typing.Callable[[], T_Result],
        spm: typing.Callable[[], T_Result],
        srb: typing.Callable[[], T_Result],
        ssd: typing.Callable[[], T_Result],
        stp: typing.Callable[[], T_Result],
        sur: typing.Callable[[], T_Result],
        svk: typing.Callable[[], T_Result],
        svn: typing.Callable[[], T_Result],
        swe: typing.Callable[[], T_Result],
        swz: typing.Callable[[], T_Result],
        sxm: typing.Callable[[], T_Result],
        syc: typing.Callable[[], T_Result],
        syr: typing.Callable[[], T_Result],
        tca: typing.Callable[[], T_Result],
        tcd: typing.Callable[[], T_Result],
        tgo: typing.Callable[[], T_Result],
        tha: typing.Callable[[], T_Result],
        tjk: typing.Callable[[], T_Result],
        tkl: typing.Callable[[], T_Result],
        tkm: typing.Callable[[], T_Result],
        tls: typing.Callable[[], T_Result],
        ton: typing.Callable[[], T_Result],
        tto: typing.Callable[[], T_Result],
        tun: typing.Callable[[], T_Result],
        tur: typing.Callable[[], T_Result],
        tuv: typing.Callable[[], T_Result],
        twn: typing.Callable[[], T_Result],
        tza: typing.Callable[[], T_Result],
        uga: typing.Callable[[], T_Result],
        ukr: typing.Callable[[], T_Result],
        umi: typing.Callable[[], T_Result],
        ury: typing.Callable[[], T_Result],
        usa: typing.Callable[[], T_Result],
        uzb: typing.Callable[[], T_Result],
        vat: typing.Callable[[], T_Result],
        vct: typing.Callable[[], T_Result],
        ven: typing.Callable[[], T_Result],
        vgb: typing.Callable[[], T_Result],
        vir: typing.Callable[[], T_Result],
        vnm: typing.Callable[[], T_Result],
        vut: typing.Callable[[], T_Result],
        wlf: typing.Callable[[], T_Result],
        wsm: typing.Callable[[], T_Result],
        yem: typing.Callable[[], T_Result],
        zaf: typing.Callable[[], T_Result],
        zmb: typing.Callable[[], T_Result],
        zwe: typing.Callable[[], T_Result],
        xxx: typing.Callable[[], T_Result],
        rks: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is Country.ABW:
            return abw()
        if self is Country.AFG:
            return afg()
        if self is Country.AGO:
            return ago()
        if self is Country.AIA:
            return aia()
        if self is Country.ALA:
            return ala()
        if self is Country.ALB:
            return alb()
        if self is Country.AND:
            return and_()
        if self is Country.ARE:
            return are()
        if self is Country.ARG:
            return arg()
        if self is Country.ARM:
            return arm()
        if self is Country.ASM:
            return asm()
        if self is Country.ATA:
            return ata()
        if self is Country.ATF:
            return atf()
        if self is Country.ATG:
            return atg()
        if self is Country.AUS:
            return aus()
        if self is Country.AUT:
            return aut()
        if self is Country.AZE:
            return aze()
        if self is Country.BDI:
            return bdi()
        if self is Country.BEL:
            return bel()
        if self is Country.BEN:
            return ben()
        if self is Country.BFA:
            return bfa()
        if self is Country.BGD:
            return bgd()
        if self is Country.BGR:
            return bgr()
        if self is Country.BHR:
            return bhr()
        if self is Country.BHS:
            return bhs()
        if self is Country.BIH:
            return bih()
        if self is Country.BLM:
            return blm()
        if self is Country.SHN:
            return shn()
        if self is Country.BLR:
            return blr()
        if self is Country.BLZ:
            return blz()
        if self is Country.BMU:
            return bmu()
        if self is Country.BOL:
            return bol()
        if self is Country.BES:
            return bes()
        if self is Country.BRA:
            return bra()
        if self is Country.BRB:
            return brb()
        if self is Country.BRN:
            return brn()
        if self is Country.BTN:
            return btn()
        if self is Country.BVT:
            return bvt()
        if self is Country.BWA:
            return bwa()
        if self is Country.CAF:
            return caf()
        if self is Country.CAN:
            return can()
        if self is Country.CCK:
            return cck()
        if self is Country.CHE:
            return che()
        if self is Country.CHL:
            return chl()
        if self is Country.CHN:
            return chn()
        if self is Country.CIV:
            return civ()
        if self is Country.CMR:
            return cmr()
        if self is Country.COD:
            return cod()
        if self is Country.COG:
            return cog()
        if self is Country.COK:
            return cok()
        if self is Country.COL:
            return col()
        if self is Country.COM:
            return com()
        if self is Country.CPV:
            return cpv()
        if self is Country.CRI:
            return cri()
        if self is Country.CUB:
            return cub()
        if self is Country.CUW:
            return cuw()
        if self is Country.CXR:
            return cxr()
        if self is Country.CYM:
            return cym()
        if self is Country.CYP:
            return cyp()
        if self is Country.CZE:
            return cze()
        if self is Country.DEU:
            return deu()
        if self is Country.DJI:
            return dji()
        if self is Country.DMA:
            return dma()
        if self is Country.DNK:
            return dnk()
        if self is Country.DOM:
            return dom()
        if self is Country.DZA:
            return dza()
        if self is Country.ECU:
            return ecu()
        if self is Country.EGY:
            return egy()
        if self is Country.ERI:
            return eri()
        if self is Country.ESH:
            return esh()
        if self is Country.ESP:
            return esp()
        if self is Country.EST:
            return est()
        if self is Country.ETH:
            return eth()
        if self is Country.FIN:
            return fin()
        if self is Country.FJI:
            return fji()
        if self is Country.FLK:
            return flk()
        if self is Country.FRA:
            return fra()
        if self is Country.FRO:
            return fro()
        if self is Country.FSM:
            return fsm()
        if self is Country.GAB:
            return gab()
        if self is Country.GBR:
            return gbr()
        if self is Country.GEO:
            return geo()
        if self is Country.GGY:
            return ggy()
        if self is Country.GHA:
            return gha()
        if self is Country.GIB:
            return gib()
        if self is Country.GIN:
            return gin()
        if self is Country.GLP:
            return glp()
        if self is Country.GMB:
            return gmb()
        if self is Country.GNB:
            return gnb()
        if self is Country.GNQ:
            return gnq()
        if self is Country.GRC:
            return grc()
        if self is Country.GRD:
            return grd()
        if self is Country.GRL:
            return grl()
        if self is Country.GTM:
            return gtm()
        if self is Country.GUF:
            return guf()
        if self is Country.GUM:
            return gum()
        if self is Country.GUY:
            return guy()
        if self is Country.HKG:
            return hkg()
        if self is Country.HMD:
            return hmd()
        if self is Country.HND:
            return hnd()
        if self is Country.HRV:
            return hrv()
        if self is Country.HTI:
            return hti()
        if self is Country.HUN:
            return hun()
        if self is Country.IDN:
            return idn()
        if self is Country.IMN:
            return imn()
        if self is Country.IND:
            return ind()
        if self is Country.IOT:
            return iot()
        if self is Country.IRL:
            return irl()
        if self is Country.IRN:
            return irn()
        if self is Country.IRQ:
            return irq()
        if self is Country.ISL:
            return isl()
        if self is Country.ISR:
            return isr()
        if self is Country.ITA:
            return ita()
        if self is Country.JAM:
            return jam()
        if self is Country.JEY:
            return jey()
        if self is Country.JOR:
            return jor()
        if self is Country.JPN:
            return jpn()
        if self is Country.KAZ:
            return kaz()
        if self is Country.KEN:
            return ken()
        if self is Country.KGZ:
            return kgz()
        if self is Country.KHM:
            return khm()
        if self is Country.KIR:
            return kir()
        if self is Country.KNA:
            return kna()
        if self is Country.KOR:
            return kor()
        if self is Country.UNK:
            return unk()
        if self is Country.KWT:
            return kwt()
        if self is Country.LAO:
            return lao()
        if self is Country.LBN:
            return lbn()
        if self is Country.LBR:
            return lbr()
        if self is Country.LBY:
            return lby()
        if self is Country.LCA:
            return lca()
        if self is Country.LIE:
            return lie()
        if self is Country.LKA:
            return lka()
        if self is Country.LSO:
            return lso()
        if self is Country.LTU:
            return ltu()
        if self is Country.LUX:
            return lux()
        if self is Country.LVA:
            return lva()
        if self is Country.MAC:
            return mac()
        if self is Country.MAF:
            return maf()
        if self is Country.MAR:
            return mar()
        if self is Country.MCO:
            return mco()
        if self is Country.MDA:
            return mda()
        if self is Country.MDG:
            return mdg()
        if self is Country.MDV:
            return mdv()
        if self is Country.MEX:
            return mex()
        if self is Country.MHL:
            return mhl()
        if self is Country.MKD:
            return mkd()
        if self is Country.MLI:
            return mli()
        if self is Country.MLT:
            return mlt()
        if self is Country.MMR:
            return mmr()
        if self is Country.MNE:
            return mne()
        if self is Country.MNG:
            return mng()
        if self is Country.MNP:
            return mnp()
        if self is Country.MOZ:
            return moz()
        if self is Country.MRT:
            return mrt()
        if self is Country.MSR:
            return msr()
        if self is Country.MTQ:
            return mtq()
        if self is Country.MUS:
            return mus()
        if self is Country.MWI:
            return mwi()
        if self is Country.MYS:
            return mys()
        if self is Country.MYT:
            return myt()
        if self is Country.NAM:
            return nam()
        if self is Country.NCL:
            return ncl()
        if self is Country.NER:
            return ner()
        if self is Country.NFK:
            return nfk()
        if self is Country.NGA:
            return nga()
        if self is Country.NIC:
            return nic()
        if self is Country.NIU:
            return niu()
        if self is Country.NLD:
            return nld()
        if self is Country.NOR:
            return nor()
        if self is Country.NPL:
            return npl()
        if self is Country.NRU:
            return nru()
        if self is Country.NZL:
            return nzl()
        if self is Country.OMN:
            return omn()
        if self is Country.PAK:
            return pak()
        if self is Country.PAN:
            return pan()
        if self is Country.PCN:
            return pcn()
        if self is Country.PER:
            return per()
        if self is Country.PHL:
            return phl()
        if self is Country.PLW:
            return plw()
        if self is Country.PNG:
            return png()
        if self is Country.POL:
            return pol()
        if self is Country.PRI:
            return pri()
        if self is Country.PRK:
            return prk()
        if self is Country.PRT:
            return prt()
        if self is Country.PRY:
            return pry()
        if self is Country.PSE:
            return pse()
        if self is Country.PYF:
            return pyf()
        if self is Country.QAT:
            return qat()
        if self is Country.REU:
            return reu()
        if self is Country.ROU:
            return rou()
        if self is Country.RUS:
            return rus()
        if self is Country.RWA:
            return rwa()
        if self is Country.SAU:
            return sau()
        if self is Country.SDN:
            return sdn()
        if self is Country.SEN:
            return sen()
        if self is Country.SGP:
            return sgp()
        if self is Country.SGS:
            return sgs()
        if self is Country.SJM:
            return sjm()
        if self is Country.SLB:
            return slb()
        if self is Country.SLE:
            return sle()
        if self is Country.SLV:
            return slv()
        if self is Country.SMR:
            return smr()
        if self is Country.SOM:
            return som()
        if self is Country.SPM:
            return spm()
        if self is Country.SRB:
            return srb()
        if self is Country.SSD:
            return ssd()
        if self is Country.STP:
            return stp()
        if self is Country.SUR:
            return sur()
        if self is Country.SVK:
            return svk()
        if self is Country.SVN:
            return svn()
        if self is Country.SWE:
            return swe()
        if self is Country.SWZ:
            return swz()
        if self is Country.SXM:
            return sxm()
        if self is Country.SYC:
            return syc()
        if self is Country.SYR:
            return syr()
        if self is Country.TCA:
            return tca()
        if self is Country.TCD:
            return tcd()
        if self is Country.TGO:
            return tgo()
        if self is Country.THA:
            return tha()
        if self is Country.TJK:
            return tjk()
        if self is Country.TKL:
            return tkl()
        if self is Country.TKM:
            return tkm()
        if self is Country.TLS:
            return tls()
        if self is Country.TON:
            return ton()
        if self is Country.TTO:
            return tto()
        if self is Country.TUN:
            return tun()
        if self is Country.TUR:
            return tur()
        if self is Country.TUV:
            return tuv()
        if self is Country.TWN:
            return twn()
        if self is Country.TZA:
            return tza()
        if self is Country.UGA:
            return uga()
        if self is Country.UKR:
            return ukr()
        if self is Country.UMI:
            return umi()
        if self is Country.URY:
            return ury()
        if self is Country.USA:
            return usa()
        if self is Country.UZB:
            return uzb()
        if self is Country.VAT:
            return vat()
        if self is Country.VCT:
            return vct()
        if self is Country.VEN:
            return ven()
        if self is Country.VGB:
            return vgb()
        if self is Country.VIR:
            return vir()
        if self is Country.VNM:
            return vnm()
        if self is Country.VUT:
            return vut()
        if self is Country.WLF:
            return wlf()
        if self is Country.WSM:
            return wsm()
        if self is Country.YEM:
            return yem()
        if self is Country.ZAF:
            return zaf()
        if self is Country.ZMB:
            return zmb()
        if self is Country.ZWE:
            return zwe()
        if self is Country.XXX:
            return xxx()
        if self is Country.RKS:
            return rks()
