# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class PersonStatusEnum(str, enum.Enum):
    BORN = "born"
    DIED = "died"
    MARRIED = "married"

    def visit(
        self,
        born: typing.Callable[[], T_Result],
        died: typing.Callable[[], T_Result],
        married: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is PersonStatusEnum.BORN:
            return born()
        if self is PersonStatusEnum.DIED:
            return died()
        if self is PersonStatusEnum.MARRIED:
            return married()
