# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class UnitEnum(str, enum.Enum):
    METRE = "metre"
    KILOGRAM = "kilogram"
    UNIT = "unit"

    def visit(
        self,
        metre: typing.Callable[[], T_Result],
        kilogram: typing.Callable[[], T_Result],
        unit: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is UnitEnum.METRE:
            return metre()
        if self is UnitEnum.KILOGRAM:
            return kilogram()
        if self is UnitEnum.UNIT:
            return unit()
