# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from .contact_type import ContactType
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class ContactProperties(UniversalBaseModel):
    date: typing.Optional[str] = pydantic.Field(default=None)
    """
    as-of date
    """

    from_date: typing.Optional[str] = pydantic.Field(default=None)
    """
    start date
    """

    to_date: typing.Optional[str] = pydantic.Field(default=None)
    """
    end date
    """

    type: typing.Optional[ContactType] = pydantic.Field(default=None)
    """
    Email, fax, phone number, or URL
    """

    value: str = pydantic.Field()
    """
    The contact detail itself (e.g., "jdoe@sayari.com", "202-555-5555")
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
