# This file was auto-generated by Fern from our API Definition.

import typing

CountryContext = typing.Union[
    typing.Literal[
        "activity_in",
        "address",
        "citizenship",
        "domicile",
        "incorporation",
        "mentioned_in",
        "nationality",
        "product_origin",
        "residence",
        "shipment_arrival",
        "shipment_departure",
        "shipment_transit",
        "vessel_flag",
    ],
    typing.Any,
]
