# This file was auto-generated by Fern from our API Definition.

import typing

Entities = typing.Union[
    typing.Literal[
        "property",
        "vessel",
        "legal_matter",
        "shipment",
        "security",
        "company",
        "person",
        "unknown",
        "tradename",
        "aircraft",
        "intellectual_property",
        "generic",
    ],
    typing.Any,
]
