# This file was auto-generated by Fern from our API Definition.

from ...base_types.types.paginated_response import PaginatedResponse
import typing
from .measurement_data import MeasurementData
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class MeasurementInfo(PaginatedResponse):
    """
    A numerical measurement of a dimension of an entity (e.g., weight) using a standard unit
    """

    data: typing.List[MeasurementData]
    next: typing.Optional[typing.Optional[typing.Any]] = None
    offset: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
