# This file was auto-generated by Fern from our API Definition.

import typing

RiskCategory = typing.Union[
    typing.Literal[
        "adverse_media",
        "environmental_risk",
        "export_controls",
        "forced_labor",
        "political_exposure",
        "possibly_same_as_network_risk",
        "regulatory_action",
        "sanctions",
    ],
    typing.Any,
]
