# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
from .risk_event_category import RiskEventCategory
import pydantic
import typing
from .currency import Currency
from .esg_event_intensity import EsgEventIntensity
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class RiskEventProperties(UniversalBaseModel):
    category: RiskEventCategory = pydantic.Field()
    """
    The high-level classification of the risk event (e.g., Organized Crime, Law Enforcement, ESG - Governance)
    """

    credibility: typing.Optional[str] = pydantic.Field(default=None)
    """
    An indicator of the reliability of the source reporting on a specific event. It can take the values 'Low', 'Medium', or 'High'. The higher the value, the more credible the source substantiating the event is considered to be.
    """

    currency: typing.Optional[Currency] = pydantic.Field(default=None)
    """
    The ISO 4217 currency code
    """

    date: typing.Optional[str] = pydantic.Field(default=None)
    """
    as-of date of attribute
    """

    dismissal_and_clearance: typing.Optional[str] = pydantic.Field(default=None)
    """
    Captures positive resolutions such as acquittals, dropped charges, overturned sentences, and removal from enforcement lists
    """

    esg_event_intensity: typing.Optional[EsgEventIntensity] = pydantic.Field(default=None)
    """
    A categorization of the impact of a specific Environmental, Social, and Governance (ESG) event on a company ranging from Low (minimal impact) to High (maximum impact).
    """

    event_stage: typing.Optional[str] = pydantic.Field(default=None)
    """
    Captures active movement in a legal, criminal, or regulatory investigation lifecycle (e.g., Investigation, Arrest, Released)
    """

    event_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Catch-all for general list tags, notices, and unstructured risk exposure where a specific procedural stage or penalty is not defined (e.g., Reputational Risk Exposure Event Type, Notice of Hearing)
    """

    extra: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    extra information of attribute
    """

    from_date: typing.Optional[str] = pydantic.Field(default=None)
    """
    start date of attribute
    """

    monetary_value: typing.Optional[float] = pydantic.Field(default=None)
    """
    The numerical financial amount associated with the event, such as a regulatory fine or penalty
    """

    penalty_and_restriction: typing.Optional[str] = pydantic.Field(default=None)
    """
    Captures tangible punitive actions, financial sanctions, operational restrictions, and guilty sentences (e.g., Fine, Debarment, Conviction)
    """

    source_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    The URL linking to the original document, article, press release, or evidence substantiating the risk event
    """

    subcategory: typing.Optional[str] = pydantic.Field(default=None)
    """
    The specific sub-classification, issue, or issuing agency associated with the event (e.g., Traffic and Distribution of Narcotics, Police - West Midlands Police - News - United Kingdom, Workplace Diversity & Inclusion)
    """

    summary: typing.Optional[str] = pydantic.Field(default=None)
    """
    A descriptive narrative summarizing the details of the risk event
    """

    title: typing.Optional[str] = pydantic.Field(default=None)
    """
    The headline or title of the supporting evidence for the risk event
    """

    to_date: typing.Optional[str] = pydantic.Field(default=None)
    """
    end date of attribute
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
