# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing
from .resolution_attr_schema import ResolutionAttrSchema
from .resolution_profile import ResolutionProfile
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class SaveProjectEntityBody(UniversalBaseModel):
    entity_ids: typing.List[str]
    attributes: ResolutionAttrSchema
    profile: ResolutionProfile

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
