# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
from .resource_type import ResourceType
import typing
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class EntityResponseData(UniversalBaseModel):
    type: ResourceType
    id: str
    project: str
    label: str
    created: str
    updated: str
    updated_by: str
    version: int
    entity_id: str
    tag_ids: typing.List[str]
    case_status: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
