name: Python SDK

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main
    tags:
      - '*'

  workflow_dispatch:

jobs:
  # TODO: add linting?

  pytest:
    name: Test
    runs-on: ubuntu-latest
    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@v4
      - name: test code
        run: |
          ls
          make setup
          pip install pytest
          pytest -v

#  run-examples:
#    name: Run examples (to look for regressions)
#    runs-on: ubuntu-latest
#    env:
#      CLIENT_ID: ${{ secrets.CLIENT_ID }}
#      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
#    steps:
#      - uses: actions/checkout@v4
#      - name: test examples (not rate limiting)
#        run: |
#          make setup
#          make local-install
#
#          echo "Running smoke test"
#          python examples/smoke-test.py
#
#          echo "Running pagination test"
#          python examples/pagination.py


  #FIXME: add integration test to confirm it is working with the most up to date bindings

  publish-test-sdk-readme:
    name: Test publishing SDK readme
    runs-on: ubuntu-latest
    needs: run-examples
    steps:
      - uses: actions/checkout@v4
      - uses: readmeio/rdme@v8
        with:
          rdme: docs docs/go_sdk.md --key=${{ secrets.README_API_KEY }}

  #FIXME: add job to release on tag

  #FIXME: add job to publish production SDK readme on tag
