name: Python SDK

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main
    tags:
      - '*'

  workflow_dispatch:

jobs:
  # TODO: add linting?

  pytest:
    name: Test
    runs-on: ubuntu-latest
    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@v4
      - name: test code
        run: |
          ls
          make setup
          pip install pytest
          pytest -v

  run-examples:
    name: Run examples (to look for regressions)
    needs: pytest
    runs-on: ubuntu-latest
    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: test examples (not rate limiting)
        run: |
          make setup
          make local-install
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "Running hello world"
          python examples/hello-world.py
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "Running smoke test"
          python examples/smoke-test.py
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "Running pagination example"
          python examples/pagination.py
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "Running screening example"
          python examples/screening.py
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "Running trade search example"
          python examples/trade-search.py
  publish-test-sdk-readme:
    name: Test publishing SDK readme
    runs-on: ubuntu-latest
    needs: run-examples
    steps:
      - uses: actions/checkout@v4
      - uses: readmeio/rdme@v8
        with:
          rdme: docs docs/python_sdk.md --key=${{ secrets.README_API_KEY }}

  #FIXME: add integration test with the most up to date generated code (inverse of what is in the fern repo)

  #FIXME: add job to release on tag

  #FIXME: add job to publish production SDK readme on tag
